### ISSUE TITLE
Unable to load with trained model weights

### ISSUE THREAD

**Issue by kabirwalia8300** [UKPLab/controlled-argument-generation#2]
I'm trying to only use the generation component and have followed the Usage steps here and on the CTRL github. However, the generated output simply repeats the last word of my prompt. 

<img width="811" alt="Screen Shot 2020-06-25 at 7 03 21 PM" src="https://user-images.githubusercontent.com/47489875/85729617-98dceb80-b716-11ea-8edb-700e66b371b1.png">

On going through the warnings and output, I find the following:
`WARNING:tensorflow:You are creating an Estimator from a Keras model manually subclassed from `Model`, that was already called on some inputs (and thus already had weights). We are currently unable to preserve the model's state (its weights) as part of the estimator in this case. Be warned that the estimator has been created using a freshly initialized version of your model.`

I found a related issue on CTRL github which was solved by updating the estimator.patch and/or keras.py files. I assume those changes are already implemented in the files in your repo. 

Any idea on how I can deal with this issue? 
- Mac OS Catalina 10
- Python 3.7 (could this be an issue?)
- Not using tensorflow-gpu (using tensorflow-1.14)

**Comment by v1nc3nt27** [comment]
Hey! No, you actually still have to update your local library files. In my ReadMe at "Installation", you can follow the link to where the application of the patch is described in the original CTRL repo. Please let me know if this doesn't solve the problem.

**Comment by kabirwalia8300** [comment]
Hey. I followed those steps as well. Applying the patch as mentioned in step two of the Usage in the CTRL repo. But i've still been getting that issue. There is no error per say - just deprecation warnings and the warning mentioned above that I believe are impacting the generation quality.

**Comment by v1nc3nt27** [comment]
Hey, in this case, can you check what results you get if you type control codes for the original pretrained model? E.g. "Politics" or so. Because I think it doesn't load any weights at all and just randomly initializes them. If that's the case, please check if you pass the correct folder (it's the folder, not the weight file). Perhaps use the absolute paths to be on the safe side.

**Comment by kabirwalia8300** [comment]
Hey, thank your response. I think I know where the issue is. I checked the weight folders after running the download_weights.sh file again (I didn't check them earlier) and they were both empty. I realized the 7za command wasn't being found on my Mac so i had to install p7zip. However, the weights folder that are made in the .sh file (i.e cc_seqlen256_v1 and reddit_seqlen256_v1) are both empty. I know I am downloading the weights correctly coz they show up in the scripts directory. I don't think the '7za x' command is working appropriately. Any ideas to fix that or any alternative?

**Comment by kabirwalia8300** [comment]
Hey, thank you for your response. I realized where the error was. On my Mac, I didn't have the p7zip package which is needed to run a 7za x command (given in the weights sh file). As a result, my weights directories were empty. Solved it using steps given at this link:

https://superuser.com/questions/548349/how-can-i-install-7zip-so-i-can-run-it-from-terminal-on-os-x

**Comment by kabirwalia8300** [comment]
I have another error that occured after I ran the generation script with the right weight directories. Should I make another issue for that for can I post it here? I'm attaching it below anyway:

2020-06-27 23:06:43.357538: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: reddit_seqlen256_v1/model.ckpt-456847.data-00000-of-00001; No such file or directory
Traceback (most recent call last):
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: reddit_seqlen256_v1/model.ckpt-456847.data-00000-of-00001; No such file or directory
	 [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1286, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: reddit_seqlen256_v1/model.ckpt-456847.data-00000-of-00001; No such file or directory
	 [[node save/RestoreV2 (defined at generation.py:163) ]]

Original stack trace for 'save/RestoreV2':
  File "generation.py", line 163, in <module>
    predict_fn = tf.contrib.predictor.from_estimator(estimator_model, serving_input_fn)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/contrib/predictor/predictor_factories.py", line 105, in from_estimator
    config=config)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/contrib/predictor/core_estimator_predictor.py", line 77, in __init__
    checkpoint_dir=checkpoint_dir))
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1007, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 725, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1200, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1205, in _create_session
    return self._sess_creator.create_session()
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 871, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 638, in create_session
    self._scaffold.finalize()
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 229, in finalize
    self._saver = training_saver._get_saver_or_default()  # pylint: disable=protected-access
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 599, in _get_saver_or_default
    saver = Saver(sharded=True, allow_empty=True)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 825, in __init__
    self.build()
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 837, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 875, in _build
    build_restore=build_restore)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 502, in _build_internal
    restore_sequentially, reshape)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 381, in _AddShardedRestoreOps
    name="restore_shard"))
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1296, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1614, in object_graph_key_mapping
    object_graph_string = reader.get_tensor(trackable.OBJECT_GRAPH_PROTO_KEY)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 678, in get_tensor
    return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str))
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generation.py", line 163, in <module>
    predict_fn = tf.contrib.predictor.from_estimator(estimator_model, serving_input_fn)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/contrib/predictor/predictor_factories.py", line 105, in from_estimator
    config=config)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/contrib/predictor/core_estimator_predictor.py", line 77, in __init__
    checkpoint_dir=checkpoint_dir))
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1007, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 725, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1200, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1205, in _create_session
    return self._sess_creator.create_session()
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 871, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 647, in create_session
    init_fn=self._scaffold.init_fn)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/session_manager.py", line 290, in prepare_session
    config=config)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/session_manager.py", line 220, in _restore_checkpoint
    saver.restore(sess, ckpt.model_checkpoint_path)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1302, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

reddit_seqlen256_v1/model.ckpt-456847.data-00000-of-00001; No such file or directory
	 [[node save/RestoreV2 (defined at generation.py:163) ]]

Original stack trace for 'save/RestoreV2':
  File "generation.py", line 163, in <module>
    predict_fn = tf.contrib.predictor.from_estimator(estimator_model, serving_input_fn)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/contrib/predictor/predictor_factories.py", line 105, in from_estimator
    config=config)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/contrib/predictor/core_estimator_predictor.py", line 77, in __init__
    checkpoint_dir=checkpoint_dir))
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1007, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 725, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1200, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1205, in _create_session
    return self._sess_creator.create_session()
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 871, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 638, in create_session
    self._scaffold.finalize()
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 229, in finalize
    self._saver = training_saver._get_saver_or_default()  # pylint: disable=protected-access
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 599, in _get_saver_or_default
    saver = Saver(sharded=True, allow_empty=True)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 825, in __init__
    self.build()
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 837, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 875, in _build
    build_restore=build_restore)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 502, in _build_internal
    restore_sequentially, reshape)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 381, in _AddShardedRestoreOps
    name="restore_shard"))
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by kabirwalia8300** [comment]
Hey so I redownloaded the weights and everything, giving the absolute path for the folder as well. It, however, is giving me the  error as given below: 

`2020-06-28 11:52:10.334424: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: /Users/kabirwalia/Desktop/controlled-argument-generation/cc_seqlen256_v1/model.ckpt-469537.data-00000-of-00001; No such file or directory
Traceback (most recent call last):
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/Users/kabirwalia/nlpDL/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: /Users/kabirwalia/Desktop/controlled-argument-generation/cc_seqlen256_v1/model.ckpt-469537.data-00000-of-00001; No such file or directory
	 [[{{node save/RestoreV2}}]]`

I checked the cc_seqlen256_v1 folder and the file exists. Any clue?

**Comment by v1nc3nt27** [comment]
Hey, can you send me the full command you use to start the model? It seems like the path is still incorrect. I have no mac so I don't know how the folder structure looks like, but make sure that the absolute path is correct (with `pwd` you can check the path) and perhaps necessary permissions to the folder are set. Based on the error, if you open a terminal and type `cd /Users/kabirwalia/Desktop/controlled-argument-generation/cc_seqlen256_v1/` it actually shouldn't work. Now that you managed to unzip the files, you could also try the relative path again by just passing `cc_seqlen256_v1`/.

**Comment by kabirwalia8300** [comment]
Below is the results of ls command for the main repo and the cc_seqlen256_v1/ directory. Right at the end, is the command i typed to generate. 

`(nlpDL) (base) kabirwalia ~/Desktop/controlled-argument-generation $ ls
CODE_OF_CONDUCT.md			control_codes.py			pytorch_transformer.py
LICENSE.txt				control_codes.txt			requirements.txt
NOTICE.txt				convert_tf_to_huggingface_pytorch.py	scripts
README.md				ctrl-merges.txt				source_attribution.py
README_original.md			ctrl-vocab.json				training_data
__pycache__				ctrl.gif				training_utils
arg_gen_pipeline.png			estimator.patch				transformer.py
cc_seqlen256_v1				generation.py				vocab
codes					pytorch_generation.py
(nlpDL) (base) kabirwalia ~/Desktop/controlled-argument-generation $ cd cc_seqlen256_v1 
(nlpDL) (base) kabirwalia ~/Desktop/controlled-argument-generation/cc_seqlen256_v1 $ ls
checkpoint					model.ckpt-469537.index
model.ckpt-469537-002.data-00000-of-00001	model.ckpt-469537.meta
(nlpDL) (base) kabirwalia ~/Desktop/controlled-argument-generation/cc_seqlen256_v1 $ python generation.py --model_dir cc_seqlen256_v1/`

**Comment by kabirwalia8300** [comment]
Fixed. Main issue was still in the p7zip file - wasn't executing the 7za command. Might be useful to include p7zip in the requirements (for Mac). Thank you for the great paper and github release!

**Comment by v1nc3nt27** [comment]
Hey, sorry that I couldn't help much with it, as I don't have a mac for testing. What was the solution, i.e. what command did you finally use to correctly unzip it? Thanks and good luck with your experiments.

**Comment by kabirwalia8300** [comment]
I uninstalled and re-installed p7zip. There was some broken file in my initial download. I ran `pip install p7zip` and went through the process of downloading the weights again and it fixed it. Thank you!
